version: '3.5'

services:
  spring_mvc-db:
    image: postgres
    container_name: library-db
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=library
    ports:
      - "5500:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data