create table if not exists users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR NOT NULL UNIQUE,
    birthday  INT    NOT NULL CHECK ( birthday > 1900 )
);

create table if not exists books
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR NOT NULL,
    author       VARCHAR NOT NULL,
    published_at INT     NOT NULL,
    user_id      BIGINT REFERENCES users (id)
);

insert into users (full_name, birthday)
VALUES ('Иванов Иван Иванович', 1970),
       ('Петров Петр Петрович', 1960),
       ('Алексеев Алексей Алексеевич', 1989),
       ('Познер Владимир Владимирович', 1944),
       ('Федоров Мирон Янович', 1985);

insert into books (title, author, published_at, user_id)
VALUES ('Над пропастью во ржи', 'Джером Сэлинджер', 1951, 1),
       ('День опричника', 'Владимир Сорокин', 2006, 2),
       ('Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018, 1),
       ('Философия Java', 'Брюс Эккель', 2018, null),
       ('Психопатология обыденной жизни', 'Фрейд Зигмунд', 1904, null),
       ('Игра в бисер', 'Герман Гессе', 1943, 1),
       ('Бытие и время', 'Мартин Хайдеггер', 1927, 3);